/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandRouteImport } from './routes/stand'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReunioesRouteImport } from './routes/reunioes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as QualificacaoRouteImport } from './routes/qualificacao'
import { Route as ProvisoesRouteImport } from './routes/provisoes'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as PreSelecaoRouteImport } from './routes/pre-selecao'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as PedidoOriginalRouteImport } from './routes/pedido-original'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NewOrderRouteImport } from './routes/new-order'
import { Route as MetasPaceRouteImport } from './routes/metas-pace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FarolRouteImport } from './routes/farol'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CondicoesPagamentoRouteImport } from './routes/condicoes-pagamento'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as StandLeadsRouteImport } from './routes/stand.leads'
import { Route as ReunioesImportarRouteImport } from './routes/reunioes.importar'
import { Route as PortalProvisoesRouteImport } from './routes/portal.provisoes'
import { Route as PortalPedidosRouteImport } from './routes/portal.pedidos'
import { Route as PortalCotacoesRouteImport } from './routes/portal.cotacoes'
import { Route as PortalContaRouteImport } from './routes/portal.conta'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSincronizacaoSncfRouteImport } from './routes/admin.sincronizacao-sncf'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPrecosRouteImport } from './routes/admin.precos'
import { Route as AdminPermissoesRouteImport } from './routes/admin.permissoes'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminGateAbRouteImport } from './routes/admin.gate-ab'
import { Route as AdminCartilhasRouteImport } from './routes/admin.cartilhas'
import { Route as AdminAccessLogsRouteImport } from './routes/admin.access-logs'
import { Route as CatalogCategoriaCategoriaRouteImport } from './routes/catalog.categoria.$categoria'

const StandRoute = StandRouteImport.update({
  id: '/stand',
  path: '/stand',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesRoute = ReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificacaoRoute = QualificacaoRouteImport.update({
  id: '/qualificacao',
  path: '/qualificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisoesRoute = ProvisoesRouteImport.update({
  id: '/provisoes',
  path: '/provisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const PreSelecaoRoute = PreSelecaoRouteImport.update({
  id: '/pre-selecao',
  path: '/pre-selecao',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOriginalRoute = PedidoOriginalRouteImport.update({
  id: '/pedido-original',
  path: '/pedido-original',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrderRoute = NewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasPaceRoute = MetasPaceRouteImport.update({
  id: '/metas-pace',
  path: '/metas-pace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarolRoute = FarolRouteImport.update({
  id: '/farol',
  path: '/farol',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicoesPagamentoRoute = CondicoesPagamentoRouteImport.update({
  id: '/condicoes-pagamento',
  path: '/condicoes-pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const StandLeadsRoute = StandLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => StandRoute,
} as any)
const ReunioesImportarRoute = ReunioesImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => ReunioesRoute,
} as any)
const PortalProvisoesRoute = PortalProvisoesRouteImport.update({
  id: '/provisoes',
  path: '/provisoes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPedidosRoute = PortalPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCotacoesRoute = PortalCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContaRoute = PortalContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => PortalRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSincronizacaoSncfRoute = AdminSincronizacaoSncfRouteImport.update({
  id: '/admin/sincronizacao-sncf',
  path: '/admin/sincronizacao-sncf',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/admin/precos',
  path: '/admin/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissoesRoute = AdminPermissoesRouteImport.update({
  id: '/admin/permissoes',
  path: '/admin/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateAbRoute = AdminGateAbRouteImport.update({
  id: '/admin/gate-ab',
  path: '/admin/gate-ab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCartilhasRoute = AdminCartilhasRouteImport.update({
  id: '/admin/cartilhas',
  path: '/admin/cartilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessLogsRoute = AdminAccessLogsRouteImport.update({
  id: '/admin/access-logs',
  path: '/admin/access-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogCategoriaCategoriaRoute =
  CatalogCategoriaCategoriaRouteImport.update({
    id: '/categoria/$categoria',
    path: '/categoria/$categoria',
    getParentRoute: () => CatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/commercial': typeof CommercialRoute
  '/condicoes-pagamento': typeof CondicoesPagamentoRoute
  '/confirmation': typeof ConfirmationRoute
  '/cotacoes': typeof CotacoesRoute
  '/dashboard': typeof DashboardRoute
  '/farol': typeof FarolRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/metas-pace': typeof MetasPaceRoute
  '/new-order': typeof NewOrderRoute
  '/orders': typeof OrdersRoute
  '/pedido-original': typeof PedidoOriginalRoute
  '/photos': typeof PhotosRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-selecao': typeof PreSelecaoRoute
  '/produto': typeof ProdutoRoute
  '/provisoes': typeof ProvisoesRoute
  '/qualificacao': typeof QualificacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reunioes': typeof ReunioesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stand': typeof StandRouteWithChildren
  '/admin/access-logs': typeof AdminAccessLogsRoute
  '/admin/cartilhas': typeof AdminCartilhasRoute
  '/admin/gate-ab': typeof AdminGateAbRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sincronizacao-sncf': typeof AdminSincronizacaoSncfRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/conta': typeof PortalContaRoute
  '/portal/cotacoes': typeof PortalCotacoesRoute
  '/portal/pedidos': typeof PortalPedidosRoute
  '/portal/provisoes': typeof PortalProvisoesRoute
  '/reunioes/importar': typeof ReunioesImportarRoute
  '/stand/leads': typeof StandLeadsRoute
  '/portal/': typeof PortalIndexRoute
  '/catalog/categoria/$categoria': typeof CatalogCategoriaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/commercial': typeof CommercialRoute
  '/condicoes-pagamento': typeof CondicoesPagamentoRoute
  '/confirmation': typeof ConfirmationRoute
  '/cotacoes': typeof CotacoesRoute
  '/dashboard': typeof DashboardRoute
  '/farol': typeof FarolRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/metas-pace': typeof MetasPaceRoute
  '/new-order': typeof NewOrderRoute
  '/orders': typeof OrdersRoute
  '/pedido-original': typeof PedidoOriginalRoute
  '/photos': typeof PhotosRoute
  '/pre-selecao': typeof PreSelecaoRoute
  '/produto': typeof ProdutoRoute
  '/provisoes': typeof ProvisoesRoute
  '/qualificacao': typeof QualificacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reunioes': typeof ReunioesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stand': typeof StandRouteWithChildren
  '/admin/access-logs': typeof AdminAccessLogsRoute
  '/admin/cartilhas': typeof AdminCartilhasRoute
  '/admin/gate-ab': typeof AdminGateAbRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sincronizacao-sncf': typeof AdminSincronizacaoSncfRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/conta': typeof PortalContaRoute
  '/portal/cotacoes': typeof PortalCotacoesRoute
  '/portal/pedidos': typeof PortalPedidosRoute
  '/portal/provisoes': typeof PortalProvisoesRoute
  '/reunioes/importar': typeof ReunioesImportarRoute
  '/stand/leads': typeof StandLeadsRoute
  '/portal': typeof PortalIndexRoute
  '/catalog/categoria/$categoria': typeof CatalogCategoriaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/commercial': typeof CommercialRoute
  '/condicoes-pagamento': typeof CondicoesPagamentoRoute
  '/confirmation': typeof ConfirmationRoute
  '/cotacoes': typeof CotacoesRoute
  '/dashboard': typeof DashboardRoute
  '/farol': typeof FarolRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/metas-pace': typeof MetasPaceRoute
  '/new-order': typeof NewOrderRoute
  '/orders': typeof OrdersRoute
  '/pedido-original': typeof PedidoOriginalRoute
  '/photos': typeof PhotosRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-selecao': typeof PreSelecaoRoute
  '/produto': typeof ProdutoRoute
  '/provisoes': typeof ProvisoesRoute
  '/qualificacao': typeof QualificacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reunioes': typeof ReunioesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/metas-pace': typeof MetasPaceRoute
  '/stand': typeof StandRouteWithChildren
  '/admin/access-logs': typeof AdminAccessLogsRoute
  '/admin/cartilhas': typeof AdminCartilhasRoute
  '/admin/gate-ab': typeof AdminGateAbRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sincronizacao-sncf': typeof AdminSincronizacaoSncfRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/conta': typeof PortalContaRoute
  '/portal/cotacoes': typeof PortalCotacoesRoute
  '/portal/pedidos': typeof PortalPedidosRoute
  '/portal/provisoes': typeof PortalProvisoesRoute
  '/reunioes/importar': typeof ReunioesImportarRoute
  '/stand/leads': typeof StandLeadsRoute
  '/portal/': typeof PortalIndexRoute
  '/catalog/categoria/$categoria': typeof CatalogCategoriaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/cart'
    | '/catalog'
    | '/clientes'
    | '/commercial'
    | '/condicoes-pagamento'
    | '/confirmation'
    | '/cotacoes'
    | '/dashboard'
    | '/farol'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/metas-pace'
    | '/new-order'
    | '/orders'
    | '/pedido-original'
    | '/photos'
    | '/portal'
    | '/pre-selecao'
    | '/produto'
    | '/provisoes'
    | '/qualificacao'
    | '/relatorios'
    | '/reset-password'
    | '/reunioes'
    | '/settings'
    | '/stand'
    | '/admin/access-logs'
    | '/admin/cartilhas'
    | '/admin/gate-ab'
    | '/admin/leads'
    | '/admin/permissoes'
    | '/admin/precos'
    | '/admin/products'
    | '/admin/sincronizacao-sncf'
    | '/admin/users'
    | '/portal/conta'
    | '/portal/cotacoes'
    | '/portal/pedidos'
    | '/portal/provisoes'
    | '/reunioes/importar'
    | '/stand/leads'
    | '/portal/'
    | '/catalog/categoria/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/cart'
    | '/catalog'
    | '/clientes'
    | '/commercial'
    | '/condicoes-pagamento'
    | '/confirmation'
    | '/cotacoes'
    | '/dashboard'
    | '/farol'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/metas-pace'
    | '/new-order'
    | '/orders'
    | '/pedido-original'
    | '/photos'
    | '/pre-selecao'
    | '/produto'
    | '/provisoes'
    | '/qualificacao'
    | '/relatorios'
    | '/reset-password'
    | '/reunioes'
    | '/settings'
    | '/stand'
    | '/admin/access-logs'
    | '/admin/cartilhas'
    | '/admin/gate-ab'
    | '/admin/leads'
    | '/admin/permissoes'
    | '/admin/precos'
    | '/admin/products'
    | '/admin/sincronizacao-sncf'
    | '/admin/users'
    | '/portal/conta'
    | '/portal/cotacoes'
    | '/portal/pedidos'
    | '/portal/provisoes'
    | '/reunioes/importar'
    | '/stand/leads'
    | '/portal'
    | '/catalog/categoria/$categoria'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/cart'
    | '/catalog'
    | '/clientes'
    | '/commercial'
    | '/condicoes-pagamento'
    | '/confirmation'
    | '/cotacoes'
    | '/dashboard'
    | '/farol'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/metas-pace'
    | '/new-order'
    | '/orders'
    | '/pedido-original'
    | '/photos'
    | '/portal'
    | '/pre-selecao'
    | '/produto'
    | '/provisoes'
    | '/qualificacao'
    | '/relatorios'
    | '/reset-password'
    | '/reunioes'
    | '/settings'
    | '/stand'
    | '/admin/access-logs'
    | '/admin/cartilhas'
    | '/admin/gate-ab'
    | '/admin/leads'
    | '/admin/permissoes'
    | '/admin/precos'
    | '/admin/products'
    | '/admin/sincronizacao-sncf'
    | '/admin/users'
    | '/portal/conta'
    | '/portal/cotacoes'
    | '/portal/pedidos'
    | '/portal/provisoes'
    | '/reunioes/importar'
    | '/stand/leads'
    | '/portal/'
    | '/catalog/categoria/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  CommercialRoute: typeof CommercialRoute
  CondicoesPagamentoRoute: typeof CondicoesPagamentoRoute
  ConfirmationRoute: typeof ConfirmationRoute
  CotacoesRoute: typeof CotacoesRoute
  DashboardRoute: typeof DashboardRoute
  FarolRoute: typeof FarolRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  MetasPaceRoute: typeof MetasPaceRoute
  NewOrderRoute: typeof NewOrderRoute
  OrdersRoute: typeof OrdersRoute
  PedidoOriginalRoute: typeof PedidoOriginalRoute
  PhotosRoute: typeof PhotosRoute
  PortalRoute: typeof PortalRouteWithChildren
  PreSelecaoRoute: typeof PreSelecaoRoute
  ProdutoRoute: typeof ProdutoRoute
  ProvisoesRoute: typeof ProvisoesRoute
  QualificacaoRoute: typeof QualificacaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReunioesRoute: typeof ReunioesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StandRoute: typeof StandRouteWithChildren
  AdminAccessLogsRoute: typeof AdminAccessLogsRoute
  AdminCartilhasRoute: typeof AdminCartilhasRoute
  AdminGateAbRoute: typeof AdminGateAbRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPermissoesRoute: typeof AdminPermissoesRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSincronizacaoSncfRoute: typeof AdminSincronizacaoSncfRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stand': {
      id: '/stand'
      path: '/stand'
      fullPath: '/stand'
      preLoaderRoute: typeof StandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes': {
      id: '/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof ReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualificacao': {
      id: '/qualificacao'
      path: '/qualificacao'
      fullPath: '/qualificacao'
      preLoaderRoute: typeof QualificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisoes': {
      id: '/provisoes'
      path: '/provisoes'
      fullPath: '/provisoes'
      preLoaderRoute: typeof ProvisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-selecao': {
      id: '/pre-selecao'
      path: '/pre-selecao'
      fullPath: '/pre-selecao'
      preLoaderRoute: typeof PreSelecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-original': {
      id: '/pedido-original'
      path: '/pedido-original'
      fullPath: '/pedido-original'
      preLoaderRoute: typeof PedidoOriginalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-order': {
      id: '/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof NewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas-pace': {
      id: '/metas-pace'
      path: '/metas-pace'
      fullPath: '/metas-pace'
      preLoaderRoute: typeof MetasPaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farol': {
      id: '/farol'
      path: '/farol'
      fullPath: '/farol'
      preLoaderRoute: typeof FarolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condicoes-pagamento': {
      id: '/condicoes-pagamento'
      path: '/condicoes-pagamento'
      fullPath: '/condicoes-pagamento'
      preLoaderRoute: typeof CondicoesPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/stand/leads': {
      id: '/stand/leads'
      path: '/leads'
      fullPath: '/stand/leads'
      preLoaderRoute: typeof StandLeadsRouteImport
      parentRoute: typeof StandRoute
    }
    '/reunioes/importar': {
      id: '/reunioes/importar'
      path: '/importar'
      fullPath: '/reunioes/importar'
      preLoaderRoute: typeof ReunioesImportarRouteImport
      parentRoute: typeof ReunioesRoute
    }
    '/portal/provisoes': {
      id: '/portal/provisoes'
      path: '/provisoes'
      fullPath: '/portal/provisoes'
      preLoaderRoute: typeof PortalProvisoesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/pedidos': {
      id: '/portal/pedidos'
      path: '/pedidos'
      fullPath: '/portal/pedidos'
      preLoaderRoute: typeof PortalPedidosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cotacoes': {
      id: '/portal/cotacoes'
      path: '/cotacoes'
      fullPath: '/portal/cotacoes'
      preLoaderRoute: typeof PortalCotacoesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/conta': {
      id: '/portal/conta'
      path: '/conta'
      fullPath: '/portal/conta'
      preLoaderRoute: typeof PortalContaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sincronizacao-sncf': {
      id: '/admin/sincronizacao-sncf'
      path: '/admin/sincronizacao-sncf'
      fullPath: '/admin/sincronizacao-sncf'
      preLoaderRoute: typeof AdminSincronizacaoSncfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/admin/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissoes': {
      id: '/admin/permissoes'
      path: '/admin/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AdminPermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gate-ab': {
      id: '/admin/gate-ab'
      path: '/admin/gate-ab'
      fullPath: '/admin/gate-ab'
      preLoaderRoute: typeof AdminGateAbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cartilhas': {
      id: '/admin/cartilhas'
      path: '/admin/cartilhas'
      fullPath: '/admin/cartilhas'
      preLoaderRoute: typeof AdminCartilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access-logs': {
      id: '/admin/access-logs'
      path: '/admin/access-logs'
      fullPath: '/admin/access-logs'
      preLoaderRoute: typeof AdminAccessLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/categoria/$categoria': {
      id: '/catalog/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/catalog/categoria/$categoria'
      preLoaderRoute: typeof CatalogCategoriaCategoriaRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogCategoriaCategoriaRoute: typeof CatalogCategoriaCategoriaRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogCategoriaCategoriaRoute: CatalogCategoriaCategoriaRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface PortalRouteChildren {
  PortalContaRoute: typeof PortalContaRoute
  PortalCotacoesRoute: typeof PortalCotacoesRoute
  PortalPedidosRoute: typeof PortalPedidosRoute
  PortalProvisoesRoute: typeof PortalProvisoesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContaRoute: PortalContaRoute,
  PortalCotacoesRoute: PortalCotacoesRoute,
  PortalPedidosRoute: PortalPedidosRoute,
  PortalProvisoesRoute: PortalProvisoesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ReunioesRouteChildren {
  ReunioesImportarRoute: typeof ReunioesImportarRoute
}

const ReunioesRouteChildren: ReunioesRouteChildren = {
  ReunioesImportarRoute: ReunioesImportarRoute,
}

const ReunioesRouteWithChildren = ReunioesRoute._addFileChildren(
  ReunioesRouteChildren,
)

interface StandRouteChildren {
  StandLeadsRoute: typeof StandLeadsRoute
}

const StandRouteChildren: StandRouteChildren = {
  StandLeadsRoute: StandLeadsRoute,
}

const StandRouteWithChildren = StandRoute._addFileChildren(StandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRouteWithChildren,
  ClientesRoute: ClientesRoute,
  CommercialRoute: CommercialRoute,
  CondicoesPagamentoRoute: CondicoesPagamentoRoute,
  ConfirmationRoute: ConfirmationRoute,
  CotacoesRoute: CotacoesRoute,
  DashboardRoute: DashboardRoute,
  FarolRoute: FarolRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  MetasPaceRoute: MetasPaceRoute,
  NewOrderRoute: NewOrderRoute,
  OrdersRoute: OrdersRoute,
  PedidoOriginalRoute: PedidoOriginalRoute,
  PhotosRoute: PhotosRoute,
  PortalRoute: PortalRouteWithChildren,
  PreSelecaoRoute: PreSelecaoRoute,
  ProdutoRoute: ProdutoRoute,
  ProvisoesRoute: ProvisoesRoute,
  QualificacaoRoute: QualificacaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReunioesRoute: ReunioesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StandRoute: StandRouteWithChildren,
  AdminAccessLogsRoute: AdminAccessLogsRoute,
  AdminCartilhasRoute: AdminCartilhasRoute,
  AdminGateAbRoute: AdminGateAbRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPermissoesRoute: AdminPermissoesRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSincronizacaoSncfRoute: AdminSincronizacaoSncfRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
