/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as NewOrderRouteImport } from './routes/new-order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CatalogCategoriaCategoriaRouteImport } from './routes/catalog.categoria.$categoria'

const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrderRoute = NewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogCategoriaCategoriaRoute =
  CatalogCategoriaCategoriaRouteImport.update({
    id: '/categoria/$categoria',
    path: '/categoria/$categoria',
    getParentRoute: () => CatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/new-order': typeof NewOrderRoute
  '/photos': typeof PhotosRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/categoria/$categoria': typeof CatalogCategoriaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/new-order': typeof NewOrderRoute
  '/photos': typeof PhotosRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/categoria/$categoria': typeof CatalogCategoriaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/new-order': typeof NewOrderRoute
  '/photos': typeof PhotosRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/categoria/$categoria': typeof CatalogCategoriaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/catalog'
    | '/confirmation'
    | '/import'
    | '/login'
    | '/new-order'
    | '/photos'
    | '/admin/users'
    | '/catalog/categoria/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/confirmation'
    | '/import'
    | '/login'
    | '/new-order'
    | '/photos'
    | '/admin/users'
    | '/catalog/categoria/$categoria'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/catalog'
    | '/confirmation'
    | '/import'
    | '/login'
    | '/new-order'
    | '/photos'
    | '/admin/users'
    | '/catalog/categoria/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  ConfirmationRoute: typeof ConfirmationRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  NewOrderRoute: typeof NewOrderRoute
  PhotosRoute: typeof PhotosRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-order': {
      id: '/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof NewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/categoria/$categoria': {
      id: '/catalog/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/catalog/categoria/$categoria'
      preLoaderRoute: typeof CatalogCategoriaCategoriaRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogCategoriaCategoriaRoute: typeof CatalogCategoriaCategoriaRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogCategoriaCategoriaRoute: CatalogCategoriaCategoriaRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRouteWithChildren,
  ConfirmationRoute: ConfirmationRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  NewOrderRoute: NewOrderRoute,
  PhotosRoute: PhotosRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
